# permissions for end users to edit reposcanners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reposcanner-editor-role
rules:
- apiGroups:
  - website.openeuler.org
  resources:
  - reposcanners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - website.openeuler.org
  resources:
  - reposcanners/status
  verbs:
  - get
