# permissions for end users to view webuis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webui-viewer-role
rules:
- apiGroups:
  - website.openeuler.org
  resources:
  - webuis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - website.openeuler.org
  resources:
  - webuis/status
  verbs:
  - get
